# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				axolotl = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				bat = true
				husk = true
				hoglin = true
				rabbit = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				shulker = true
				salmon = true
				wither_skeleton = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				horse = true
				phantom = true
				minecart = true
				ender_dragon = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				enderman = true
				chicken = true
				donkey = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				slime = true
				iron_golem = true
				zombified_piglin = true
				piglin = true
				blaze = true
				endermite = true
				cat = true
				zombie = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				villager = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.graveyard]
				revenant = true
				skeleton_creeper = true
				ghoul = true
				nightmare = true

			[light_sources.settings.entities.immersive_portals]
				loading_indicator = true

			[light_sources.settings.entities.charm]
				moobloom = true

			[light_sources.settings.entities.creeperoverhaul]
				bamboo_creeper = true
				desert_creeper = true
				dark_oak_creeper = true
				jungle_creeper = true
				dripstone_creeper = true
				cave_creeper = true
				hills_creeper = true

